### ISSUE TITLE
Cannot assume 'window' exists. 

### ISSUE THREAD

**Issue by vladikoff** [leobalter/DexterJS#19]
Hey! Trying to use this library via the Dojo AMD loader and having trouble when calling
`var fakeXHR = Dexter.fakeXHR();`:

```
Defaulting to "console" reporter
ReferenceError: window is not defined
    at /Users/vladikoff/mozilla/fxa-js-client/node_modules/dexter/dist/dexter.js:96:9
    at /Users/vladikoff/mozilla/fxa-js-client/node_modules/dexter/dist/dexter.js:109:2
    at Function.vm.runInThisContext (/Users/vladikoff/mozilla/fxa-js-client/node_modules/intern/node_modules/istanbul/lib/hook.js:163:16)
    at /Users/vladikoff/mozilla/fxa-js-client/node_modules/intern/node_modules/dojo/dojo.js:757:8
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

Code Issue:

```
    if ( typeof module === 'undefined' || typeof module.exports === 'undefined' ) {
        window.Dexter = Dexter;
    } else {
```

I'll try to PR a fix if I have time.

**Comment by leobalter** [comment]
@vladikoff would you check if 0.5.3 is working?

**Comment by vladikoff** [comment]
Oh man so sorry I missed the notification on this one, will test ASAP

**Comment by vladikoff** [comment]
Testing this straight up with Dojo's AMD loader gives me: 

```
TypeError: Object not-a-module has no method 'fake'
```

with something like that:

```
define([
  'intern!tdd',
  'intern/chai!assert',
  'tests/addons/environment',
  'components/dexter/dist/dexter'
], function (tdd, assert, Environment, Dexter) {

  with (tdd) {
    suite('test', function () {

      test('#someTest', function () {

         console.log(Dexter);
/// ...
```
